import { EditorThemeClasses } from 'lexical';
import './editor-theme.css';

export const editorTheme: EditorThemeClasses = {
	blockCursor: 'EditorTheme__blockCursor',
	code: 'EditorTheme__code',
	codeHighlight: {
		atrule: 'text-[#07a]',
		attr: 'text-[#07a]',
		boolean: 'text-[#905]',
		builtin: 'text-[#690]',
		cdata: 'text-[#708090]',
		char: 'text-[#690]',
		class: 'text-[#dd4a68]',
		'class-name': 'text-[#dd4a68]',
		comment: 'text-[#708090]',
		constant: 'text-[#905]',
		deleted: 'text-[#905]',
		doctype: 'text-[#708090]',
		entity: 'text-[#9a6e3a]',
		function: 'text-[#dd4a68]',
		important: 'text-[#e90]',
		inserted: 'text-[#690]',
		keyword: 'text-[#07a]',
		namespace: 'text-[#e90]',
		number: 'text-[#905]',
		operator: 'text-[#9a6e3a]',
		prolog: 'text-[#708090]',
		property: 'text-[#905]',
		punctuation: 'text-[#999]',
		regex: 'text-[#e90]',
		selector: 'text-[#690]',
		string: 'text-[#690]',
		symbol: 'text-[#905]',
		tag: 'text-[#905]',
		url: 'text-[#9a6e3a]',
		variable: 'text-[#e90]',
	},
	embedBlock: {
		base: 'select-none',
		focus: 'outline outline-2 outline-blue-500',
	},
	hashtag: 'bg-[rgba(35,131,226,0.1)] text-[rgb(35,131,226)] px-1 rounded',
	heading: {
		h1: 'text-[1.875em] font-bold leading-[1.3] mt-[0.5em] mb-[5px] text-[rgb(55,53,47)]',
		h2: 'text-[1.5em] font-semibold leading-[1.3] mt-[0.5em] mb-px text-[rgb(55,53,47)]',
		h3: 'text-[1.25em] font-semibold leading-[1.3] mt-[0.5em] mb-px text-[rgb(55,53,47)]',
		h4: 'text-base font-semibold leading-[1.3] mt-[0.5em] mb-px text-[rgb(55,53,47)]',
		h5: 'text-sm font-semibold leading-[1.3] mt-[0.5em] mb-px text-[rgb(55,53,47)]',
		h6: 'text-xs font-semibold leading-[1.3] mt-[0.5em] mb-px text-[rgb(55,53,47)]',
	},
	hr: 'EditorTheme__hr',
	image: 'editor-image',
	indent: '[--lexical-indent-base-value:24px]',
	link: 'text-[rgb(55,53,47)] underline decoration-[rgba(55,53,47,0.4)] underline-offset-2 hover:decoration-[rgb(55,53,47)] cursor-pointer',
	list: {
		checklist: '',
		listitem:
			'm-0 pl-[0.2em] leading-normal text-[rgb(55,53,47)] marker:text-[rgb(55,53,47)]',
		listitemChecked: 'EditorTheme__listItemChecked',
		listitemUnchecked: 'EditorTheme__listItemUnchecked',
		nested: {
			listitem: 'list-none before:hidden after:hidden',
		},
		olDepth: [
			'm-0 pl-6 list-outside list-decimal',
			'm-0 pl-6 list-outside list-[lower-alpha]',
			'm-0 pl-6 list-outside list-[lower-roman]',
			'm-0 pl-6 list-outside list-decimal',
			'm-0 pl-6 list-outside list-[lower-alpha]',
		],
		ul: 'm-0 pl-6 list-outside list-disc',
	},
	paragraph: 'm-0 relative leading-normal text-[rgb(55,53,47)]',
	quote: 'my-1 pl-3.5 border-l-[3px] border-[rgb(55,53,47)] text-[inherit] text-[rgb(55,53,47)]',
	tab: 'EditorTheme__tabNode',
	text: {
		bold: 'font-semibold',
		capitalize: 'capitalize',
		code: 'bg-[rgba(135,131,120,0.15)] rounded px-[0.4em] py-[0.2em] font-mono text-[85%] text-[#eb5757]',
		highlight: 'bg-[rgb(251,243,219)] px-0.5 -mx-0.5',
		italic: 'italic',
		lowercase: 'lowercase',
		strikethrough: 'line-through',
		subscript: 'text-[0.8em] align-sub',
		superscript: 'text-[0.8em] align-super',
		underline: 'underline',
		underlineStrikethrough: 'underline line-through',
		uppercase: 'uppercase',
	},
};
